base_stage:
  project_name: moonunit
  aws_environment_variables:
    STACK_NAME: {stack_name}
    SOURCE_BUCKET_NAME: {source_bucket_name}
    ASSETS_BUCKET_NAME: {assets_bucket_name}
  debug: true
  log_level: DEBUG
  apigateway_description: Moonunit API Endpoint to write files to S3
  lambda_description: Moonunit lambda handler
  app_function: moonunit.ingress_handler.app
  aws_region: {region}
  runtime: python3.6
  s3_bucket: moonunitco-zappa-stage
  timeout_seconds: 15
  memory_size: 128
  attach_policy: tmp/attach_policy.json
  events:
  - function: moonunit.rotate_image
    event_source:
      arn: arn:aws:s3:::{source_bucket_name}
      events:
      - s3:ObjectCreated:*

dev_{username}:
  extends: base_stage

sandbox:
  extends: base_stage
  domain: moonunit-webhook-sandbox.example.org
  certificate_arn: arn:aws:acm:us-east-1:XXXXXXXXXXXXXX:certificate/XXXX-XXXX-XXXX-XXXX

qa:
  extends: base_stage
  domain: moonunit-webhook-qa.example.org
  certificate_arn: arn:aws:acm:us-east-1:XXXXXXXXXXXXXX:certificate/XXXX-XXXX-XXXX-XXXX

production:
  extends: base_stage
  domain: moonunit-webhook.example.com
  certificate_arn: arn:aws:acm:us-east-1:XXXXXXXXXXXXXX:certificate/XXXX-XXXX-XXXX-XXXX
